scalar Date

type Admin {
  _id: ID
  organizationName: String!
  abnDuns: String
  organizationType: String!
  phoneNumber: String
  organizationAddress: String
  organizationCountry: String!
  referenceId: String!
  adminFirstName: String!
  adminLastName: String!
  adminEmailAddress: String!
  adminMobileNumber: String!
  adminPassword: String!
  billingContactName: String
  billingEmailAddress: String
  billingAddress: String
  billingPhoneNumber: String
  adminId: ID
  isDisabled: Boolean
  userType: String
  mfaEnabled: Boolean!
  mfaCode: String
  createdAt: Date
  updatedAt: Date
  deletedAt: Date
  mfaExpiry: Date
}

input AdminInput {
  organizationName: String!
  abnDuns: String
  organizationType: String!
  phoneNumber: String
  organizationAddress: String
  organizationCountry: String!
  referenceId: String!
  adminFirstName: String!
  adminLastName: String!
  adminEmailAddress: String!
  adminMobileNumber: String!
  adminPassword: String!
  billingContactName: String
  billingEmailAddress: String
  billingAddress: String
  billingPhoneNumber: String
  adminId: ID
  isDisabled: Boolean
}

type Query {
  admins: [Admin]!
  admin(id: ID!): Admin
}

type Mutation {
  createAdmin(input: AdminInput): Admin
  updateAdmin(id: ID!, input: AdminInput!): Admin!
  deleteAdmin(id: ID!): Admin!
  readAllAdmin: [Admin]!
  toggleAdminDisabled(id: ID!): Admin!
  adminLogin(email: String!, password: String!, mfaCode: String): Admin
  enableMFA(email: String): Boolean
  checkIfRefferenceIdExist(referenceId: String): Boolean
}
