type Query {
  getSleepData: String
  getHeartRateData: String!
  getHRVData: String!
  getRespiratoryRateData: String!
  getStepsData: String!
  getAccelerometerData: String!
  isDeviceOnline: Boolean!
  isDeviceOnWrist: Boolean!
  isDeviceCharging: Boolean!
  getLocationData: String!
}

type Mutation {
  sendPushNotification(message: String!): PushNotificationResponse!
  syncDataToServer: SyncResponse!
}

type SleepData {
  timeOfDay: String!
  duration: Int!
  quality: String!
}

type HeartRateData {
  timeOfDay: String!
  heartRate: Int!
}

type HRVData {
  timeOfDay: String!
  hrv: Int!
}

type RespiratoryRateData {
  timeOfDay: String!
  respiratoryRate: Int!
}

type StepsData {
  timeOfDay: String!
  steps: Int!
}

type AccelerometerData {
  timeOfDay: String!
  x: Float!
  y: Float!
  z: Float!
}

type LocationData {
  latitude: Float!
  longitude: Float!
}

type PushNotificationResponse {
  success: Boolean!
  message: String!
}

type SyncResponse {
  success: Boolean!
  message: String!
}
