type HospitalAdmin {
  id: ID!
  abnDuns: String
  phoneNumber: String
  referenceId: String!
  adminFirstName: String!
  adminLastName: String!
  adminEmailAddress: String!
  adminMobileNumber: String!
  adminPassword: String!
  billingContactName: String
  billingEmailAddress: String
  billingAddress: String
  billingPhoneNumber: String
  adminId: ID
  isDisabled: Boolean
}

input HospitalAdminInput {
  abnDuns: String
  phoneNumber: String
  referenceId: String!
  adminFirstName: String!
  adminLastName: String!
  adminEmailAddress: String!
  adminMobileNumber: String!
  adminPassword: String!
  billingContactName: String
  billingEmailAddress: String
  billingAddress: String
  billingPhoneNumber: String
  adminId: ID
  isDisabled: Boolean
}

type Query {
  hospitalAdmins: [HospitalAdmin]!
  hospitalAdmin(id: ID!): HospitalAdmin
}

type Mutation {
  createHospitalAdmin(input: AdminInput): Admin
  updateHospitalAdmin(id: ID!, input: AdminInput!): Admin!
  deleteHospitalAdmin(id: ID!): Admin!
  readAllHospitalAdmin: [Admin]!
  toggleHospitalAdminDisabled(id: ID!): Admin!
  hospitalAdminLogin(email: String!, password: String!): Admin
}
