scalar Date

type User {
  _id: ID
  firstName: String!
  middleName: String
  lastName: String!
  mobileNumber: String!
  otherPhone: String
  email: String!
  address: String!
  birthDate: String!
  gender: String!
  occupation: String
  height: String
  weight: String
  password: String!
  medication: String
  culturalBackground: String
  socialEngagements: String
  exercise: String
  referenceId: String
  anyMedication: String
  medicalConditions: [String]
  otherMedicalCondition: String
  otherPrefixNumber: String
  prefixNumber: String
  createdAt: Date
  updatedAt: Date
  deletedAt: Date
  mfaEnabled: Boolean
  mfaCode: String
  mfaExpiry: Date
}

input UserInput {
  firstName: String!
  middleName: String
  lastName: String!
  mobileNumber: String!
  otherPhone: String
  email: String!
  address: String!
  birthDate: String!
  gender: String!
  occupation: String
  height: String
  weight: String
  password: String!
  medication: String
  culturalBackground: String
  socialEngagements: String
  exercise: String
  referenceId: String
  medicalConditions: [String]
  otherMedicalCondition: String
  otherPrefixNumber: String
  prefixNumber: String
  anyMedication: String
}

input EditUserInput {
  firstName: String!
  middleName: String
  lastName: String!
  mobileNumber: String!
  otherPhone: String
  email: String!
  address: String!
  birthDate: String!
  gender: String!
  occupation: String
  height: String
  weight: String
  medicalCondition: String
  password: String!
  medication: String
  culturalBackground: String
  socialEngagements: String
  exercise: String
  referenceId: String
  anyMedication: String
  medicalConditions: [String]
  otherMedicalCondition: String
  otherPrefixNumber: String
  prefixNumber: String
}

type Query {
  users: [User]!
  user(id: ID!): User
}

type Mutation {
  createUser(input: UserInput): User
  updateUser(id: ID!, input: EditUserInput): User!
  deleteUser(id: ID!): User!
  readAllUsers(referenceId: String!): [User]!
  toggleUserDisabled(id: ID!): User!
  userLogin(email: String!, password: String!): User
  validateMFAUser(email: String!, mfaCode: String): Boolean
}
